### ISSUE TITLE
[feature request] pmtiles-import (bulk load)

### ISSUE THREAD

**Issue by tobwen** [protomaps/PMTiles#164]
## feature request
For historical reasons (e.g. using QGIS and Mapnik), I have a lot of XYZ directories with millions of files. Would it be possible to bulk load these into PMTiles (respecting XYZ- and TMS-schemes)? Probably the effort is too high for the low demand.

## work-around
Possible workarounds are rio and mb-util with middleformat mbtiles, but thanks to the limitation of single-thread sqlite writing, this will take hours.

**Comment by tobwen** [comment]
## update
I just saw that I could write my own tool to do that: https://github.com/protomaps/PMTiles/blob/main/python/examples/create_raster_example.py

I'll keep this issue open, perhaps you want to participate or discuss an integration into the core. If not, you can close it.

**Comment by bdon** [comment]
There's a couple things to consider here:

* For efficiency reasons I'd prefer to implement this in [go-pmtiles](https://github.com/protomaps/go-pmtiles) as `pmtiles convert directory_with_zxy output.pmtiles` instead of Python, for a standard command line tool
* Raw directories often lack the necessary metadata such as `bounds`, tile type, and more required by mb/pmtiles. Is this something you have stored already in a JSON file, etc?

Because this seems like a niche use case it might be preferable to let power users implement it themselves like you did with the Python library, which might be efficient enough, though there are still some rough edges we need to work out.
