### ISSUE TITLE
Cloudflare worker TileJSON endpoint

### ISSUE THREAD

**Issue by wipfli** [protomaps/PMTiles#169]
Would be nice if the cloudflare worker could return a TileJSON for each PMTiles file

https://github.com/protomaps/PMTiles/blob/main/serverless/cloudflare/src/index.ts#L241

**Comment by bdon** [comment]
@wipfli have a proof of concept in PR. I think we can advertise this as a "TileJSON-like" response which returns a superset of [TileJSON 3.0](https://github.com/mapbox/tilejson-spec/tree/master/3.0.0#3-structure). 

This also fetches all the PMTiles JSON metadata and then merges in well known keys. For a planetiler-derived basemap tileset with hundreds of OSM `name:*` tags in `vector_layers` this means the TileJSON is ~26 KB compressed. 

Should we merge the concepts of `vector_layers` metadata and TileJSON? If you are requesting one, will you need both, or should we make `tileset.json` as compact as possible? The TileJSON spec allows arbitrary other keys.

**Comment by wipfli** [comment]
I would keep tileset.json as compact as possible.

**Comment by bdon** [comment]
@wipfli looking at this closer, since TileJSON specifies `vector_layers` we really need to include this mass of metadata in the response. I wonder if we should add a planetiler feature for "truncated" metadata where only the most common keys are included?

**Comment by wipfli** [comment]
Sounds like a good idea to me.

**Comment by asebert-caue** [comment]
It would be great to have this endpoint for the Cloudflare worker!! It would make it easier to create MapLibre styles with the help of Maputnik or MapLibre-GL-Inspect in order to obtain the names of the layers and fields.

**Comment by bdon** [comment]
Right now this is blocked on implementing the following part of TileJSON: [3.2 tiles](https://github.com/mapbox/tilejson-spec/tree/master/3.0.0#32-tiles)

> An array of tile endpoints. {z}, {x} and {y}, if present, are replaced with the corresponding integers. If multiple endpoints are specified, clients may use any combination of endpoints. All endpoint urls MUST be absolute.

The *absolute endpoints* is tricky to implement because the Cloudflare Worker or AWS Lambda may not be aware of the actual CDN URLs the tiles are being accessed through. We need to implement provider-specific logic to determine this inside the function invocation - it would be a pretty bad design to require the absolute URL to be hardcoded by the developer. 

As an alternative, we can not follow TileJSON and allow relative URLs - this could also conflict with the current configuration option for `TILES_PATH`. (not sure if people are actually using this.)

So some potential next steps:

* deprecate `TILES_PATH` as a serverless configuration option
* Require JSON descriptors have the path `/NAME.json` next to `NAME/{z}/{x}/{y}.{ext}`
* Create an alternate to TileJSON with less legacy features, allowing relative paths, and allowing non-exhaustive `vector_layers`
* Otherwise, see if TileJSON clients actually accept relative tile paths or ignore tile paths (unlikely)

**Comment by asebert-caue** [comment]
I recently tested if TileJSON clients actually accept relative tile paths or ignore tile paths  with a fake TileJSON file. **Maplibre GL JS cannot load a TileJSON schema that contains relative URLs**.

With an absolute URL, Maplibre attempted to load the tiles : [https://jsfiddle.net/asebert62/4p7sc2tz/5/](https://jsfiddle.net/asebert62/4p7sc2tz/5/).
However, with a relative URL, I received a client error : [https://jsfiddle.net/asebert62/kdL57hr0/8/](https://jsfiddle.net/asebert62/kdL57hr0/8/)

`"Uncaught TypeError: Failed to construct 'Request': Failed to parse URL from /sect-humide/14/8383/5549.pbf".`

**Comment by bdon** [comment]
The conclusion here is that we must implement Absolute URLs for the TileJSON to be useful. The current CDN integrations:

* Cloudflare: since every request is a Workers invocation, we should have access to the 
* AWS: The existing integration is based on Lambda Function URLs. If you create a lambda that returns exactly the input:

```js
export const handler = async(event) => {
    return {
        statusCode: 200,
        body: JSON.stringify(event),
    };
};
```

and put CloudFront in front of this endpoint, you will see that `headers.host` is the lambda URL (you don't want this), and `headers.via` is "1.1 yourdistribution.cloudfront.net (CloudFront)". So one solution is to parse the `via` HTTP header to determine the proxy that the browser interacted with. This introduces an additional problem with caching. If there are multiple custom domains attached to the CloudFront distribution, like `tiles1.example.com` and `tiles2.example.com`, it would be bad if asking for `tiles1.example.com/tileset.json` returned `tiles2` or whatever was first cached.

It might be possible to work around this with a custom CloudFront cache policy.

**Comment by bdon** [comment]
I tested assigning custom domain names to a CloudFront distribution and this is not forwarded at all to the lambda. So it does look like the only consistent way to do this is require the developer to set a required env var like `PUBLIC_TILE_HOST` = `mytiles.example.com` just to power TileJSON absolute URLs.

**Comment by bdon** [comment]
See also potential Azure support: #197

**Comment by asebert-caue** [comment]
I think the ﻿`PUBLIC_TILE_HOST` variable could be a good compromise. As for CloudFlare, if the variable is not defined, the host present in the request header can be used by default: [https://community.cloudflare.com/t/get-the-request-host-in-the-worker/154928/2](https://community.cloudflare.com/t/get-the-request-host-in-the-worker/154928/2)

**Comment by bdon** [comment]
Yeah, I confirmed that `request.headers` `host` value on cloudflare correctly forwards the original hostname the browser interacted with. So my thinking is:

* On AWS, have TileJSON return an error message if `PUBLIC_TILE_HOST` is not configured
* On Cloudflare, default to `request.headers.host` but make it overridable with `PUBLIC_TILE_HOST`
* On Azure or other platforms we have `PUBLIC_TILE_HOST` as a fallback
* TileJSON defaults to `NAME.json` next to `PATH/{z}/{x}/{y}.mvt` paths
* I am going to remove the docs around `TILE_PATH` because the original user for that feature didn't end up needing it, I believe and that will simplify the above default paths for TileJSON


Future steps:
* Likely deprecate `TILE_PATH`
* Add a `/metadata.json` endpoint as well that returns only the PMTiles metadata object. Some of the metadata like `vector_layers` will be read into the TileJSON document, but not necessarily all.

Alternatively, we can have TileJSON return all metadata including any extra keys.

**Comment by bdon** [comment]
PR updated at https://github.com/protomaps/PMTiles/pull/170

**Comment by bdon** [comment]
I've updated the docs:

https://protomaps.com/docs/cdn/cloudflare
https://protomaps.com/docs/cdn/aws

The `PUBLIC_HOSTNAME` configuration is required on AWS for TileJSON to work properly.
