### ISSUE TITLE
Azure and Google Cloud CDN support

### ISSUE THREAD

**Issue by bdon** [protomaps/PMTiles#174]
Determine the right set of services to use for each analogous to Cloudflare / AWS.

**Comment by bdon** [comment]
# Findings

## Azure

* *Azure Front Door* seems to be the preferred CDN deployment, but has a $35 min monthly fee
* *Azure Functions* supports NodeJS, meaning it should be able to share code with CF/AWS; getting it to communicate and authenticate with Storage Buckets is tricky

## Google Cloud

* *Cloud CDN* cannot communicate directly with Cloud Run or Cloud Functions without a Load Balancer?
* *Cloud CDN* cannot do dynamic CORS?

More to come.

**Comment by sebastus** [comment]
Hi Bruce. Are you considering any other ways to enable Azure as a backend? For example, Azure Blob Storage as a source of the pmtiles file?

**Comment by tengl** [comment]
I uploaded the pmtiles file to the `$web` folder (static web site) in an Azure Blob Storage. Base on the logic for AWS and Cloudflare, I made a Function App that translates zxy urls to requests with a `Range` header using `FetchSource`. It is more generic since the pmtiles file can be published anywhere, but the entry point is of course specific to Azure Function Apps.

I don't know if accessing the pmtiles file directly using some other API would improve performance, but if you put it behind a CDN it will be fast as long as it hits the cache. 

If you like I can make a PR with the code.

**Comment by tengl** [comment]
I created a pull request #197. 

I found out that the pmtiles file doesn't have to be in the `$web` (static web site) folder, I only forgot to set access level on the container, that is why it didn't work for me.

**Comment by bdon** [comment]
Thanks, see comment https://github.com/protomaps/PMTiles/pull/197#issuecomment-1595486386 for next steps

**Comment by bdon** [comment]
Google Cloud: https://docs.protomaps.com/deploy/google-cloud
Azure PR: https://github.com/protomaps/docs/pull/52

Both use the Dockerized [go-pmtiles](https://github.com/protomaps/go-pmtiles) so don't have much platform-specific code.
