### ISSUE TITLE
Viewer should (optionally?) focus on bounds of pmtiles file

### ISSUE THREAD

**Issue by iandees** [protomaps/PMTiles#246]
I created a PMtiles from OpenAddresses data and am linking to the PMTiles Viewer from a PR ([example PR](https://github.com/openaddresses/openaddresses/pull/6915), [example pmtiles](https://pub-ef300f2557d1441981e249a936132155.r2.dev/runs/gh-bc6d820/us/mn/anoka/parcels/slippymap.pmtiles
)). That pmtiles is generated from tippecanoe, which adds the pseudo-standard bounds to the metadata.

Instead of starting the viewer at 0/0/0, could it focus on the bounds of the dataset in the pmtiles?

**Comment by bdon** [comment]
Weird, this worked before but seems to be broken on main - will investigate

**Comment by bdon** [comment]
@iandees this does seem to be working at [hotlink](https://protomaps.github.io/PMTiles/?url=https%3A%2F%2Fpub-ef300f2557d1441981e249a936132155.r2.dev%2Fruns%2Fgh-bc6d820%2Fus%2Fmn%2Fanoka%2Fparcels%2Fslippymap.pmtiles#map=9.09/45.2253/-93.2656)

maybe it's flaky because of async?

Something I noticed is that when you interact with the viewer, it will persist the map hash state upon any panning/zooming, and if you navigate and load an old file that hash will persist. So we may just need a "reset" of the state if you're explicitly navigating away in the map. 

We do want to preserve it where you open your own archive, zoom to a specific area, and can share that view via URL.

**Comment by iandees** [comment]
I think if you [hotlink](https://protomaps.github.io/PMTiles/?url=https://pub-ef300f2557d1441981e249a936132155.r2.dev/runs/gh-bc6d820/us/mn/anoka/parcels/slippymap.pmtiles) to the URL without escaping the `url` param, it won't autozoom properly.

**Comment by bdon** [comment]
(Creating a hotlink here for my own debugging, as the URL bar escapes automatically)

[hotlink](http://localhost:3000/PMTiles/?url=https://pub-ef300f2557d1441981e249a936132155.r2.dev/runs/gh-bc6d820/us/mn/anoka/parcels/slippymap.pmtiles)

**Comment by bdon** [comment]
@iandees pushed a fix, seems to be working for me (the behavior was different whether I had the console open or not, race condition related to detecting if a map hash was passed) - reopen if still has issue
