### ISSUE TITLE
Keep tiles gzipped

### ISSUE THREAD

**Issue by msbarry** [protomaps/PMTiles#26]
The pmtiles writer ungzips tiles before adding to the archive. Would it be possible to have an option to keep them gzipped? It reduces the file size substantially, and clients could use something like [pako](https://github.com/nodeca/pako) to inflate on the client side until transfer-encoding: gzip is better supported.

**Comment by bdon** [comment]
Working on this! it's useful for non-browser use cases as well. 

Clients would need to either detect the encoding scheme via parsing the JSON metadata or look at the first bytes of the tile data for the magic number. I'll probably just support gzip for now - at some point it is worth quantifying the benefit of Brotli for e.g. basemap vector tiles:

https://github.com/Qwant/qwantmaps/issues/14

**Comment by bdon** [comment]
python v1.0.0 released https://pypi.org/project/pmtiles/

the `--gzip` flag to `pmtiles-convert` now explicitly controls the tile-level compression of the output. This is default off for now,  because of the above limitations on `transfer-encoding`, but we should evaluate if enabling by default makes sense - this means all web-based clients need to bring their own decompression

https://protomaps.github.io/PMTiles/examples/inspector.html has been updated to handle `gzip`-compressed tiles using the [Pako](https://github.com/nodeca/pako) library.
