### ISSUE TITLE
Unused variable on the addProtocol function

### ISSUE THREAD

**Issue by jimmyrocks** [protomaps/PMTiles#28]
`maplibregl` should be `maplibre_instance` on this line.

https://github.com/protomaps/PMTiles/blob/fd1f5eeb39d382f7915fb9792df2f4c8935729d3/js/index.src.mjs#L203

**Comment by bdon** [comment]
I'm trying to rethink this API. The `addProtocol` is actually on the global `maplibre` module: https://maplibre.org/maplibre-gl-js-docs/api/properties/#addprotocol instead of one particular `maplibre.Map` instance. 

The reason it looks funny is because we create a `Map<string,PMTiles>` to store one PMTiles instance for every PMTiles URL referenced inside a map source - this is hidden inside the closure created by `pmtiles.addProtocol`. It would be more explicit if that function just didn't take any arguments (it doesn't actually use them) and maybe exposed the internal `<ap<string,PMTiles>` for inspecting purposes.

**Comment by bdon** [comment]
To elaborate more on this issue, related to limited-area bounds:
```js
            pmtiles.addProtocol(maplibregl)
            const map = new maplibregl.Map({
              container: 'map'
            })

            const p = new pmtiles.PMTiles("http://localhost:3857/tiles.pmtiles")
            p.metadata().then(m => {
                let bounds = m.bounds.split(',')
                let style = protomaps_themes_base.json_style('light',{
                    glyphs:'https://cdn.protomaps.com/fonts/pbf/{fontstack}/{range}.pbf',
                    tiles:"pmtiles://http://localhost:3857/tiles.pmtiles/{z}/{x}/{y}",
                    bounds:[+bounds[0],+bounds[1],+bounds[2],+bounds[3]]
                })
                map.setStyle(style)
                map.fitBounds([
                    [+bounds[0], +bounds[1]],
                    [+bounds[2], +bounds[3]]
                ],{animate:false})
            })
```

There are 3 relevant events here:
1. The "protocol" is loaded via the `maplibre.addProtocol` module-level function.
2. The metadata for the map tiles are fetched via PMTiles `metadata()` to get the bounds.
3. The map "style" is created, initializing the source with `bounds` key which limits the request area.

One limitation of MapLibre protocols is they always expect a response back because every loaded tile corresponds to a protocol invocation. It's more ideal for irrelevant tiles to never get requested at all, but we need to know the `bounds` before loading the map at all.

**Comment by bdon** [comment]
v1.0.0 is on NPM now and introduces a new cleaner API for this:

```js
let cache = new pmtiles.ProtocolCache();
maplibregl.addProtocol("pmtiles",cache.protocol);
```

The `ProtocolCache` has as `get` method to access the PMTiles instance keyed by the URL, which can be used to ensure there aren't duplicate header requests if you interact with the PMTiles outside of the MapLibre style definition.
