### ISSUE TITLE
format may be missing in mbtiles_metadata

### ISSUE THREAD

**Issue by prusswan** [protomaps/PMTiles#306]
I had to modify the lines below to get the converter to work:

https://github.com/protomaps/PMTiles/blob/e1228f5df1a4ac852e0117dc08c8813089a5c8af/python/pmtiles/convert.py#L29

https://github.com/protomaps/PMTiles/blob/e1228f5df1a4ac852e0117dc08c8813089a5c8af/python/pmtiles/convert.py#L71

Suggestion: to allow a default format to be specified by the user, e.g. 

```Python
def mbtiles_to_header_json(mbtiles_metadata, default_format=None):
    # ....
    tile_format = mbtiles_metadata.get("format", default_format)
```

Other changes may be needed for the command line option (I did not use that)

**Comment by bdon** [comment]
Sure, since there is existing software generating old specs. Any reason you don't prefer to use https://github.com/protomaps/go-pmtiles for command line conversion?

**Comment by bdon** [comment]
I'm going to close this, because most up-to-date software creates MBTiles 1.1.

If you have a 1.0 .mbtiles, you can add the required column via the `sqlite3` cli: `insert into metadata (name, value) values ("format","pbf")` etc.

If anyone can find an open source program that is still creating v1.0 we can work to update that software.
