### ISSUE TITLE
Load testing on PMTiles

### ISSUE THREAD

**Issue by xinyuluo** [protomaps/PMTiles#31]
Hi, thanks for the awesome project!

I'm trying to use pmtiles as basemap in my map project, and I would like to do some load testing on it. Normally I use [siege](https://github.com/JoeDog/siege) for this kind of testing and I'll feed URLs with randomised zoom level and x, y values.

I wonder if I could do something similar for pmtiles? If so, how would the URL look like in this case?

FYI, I'm using MaplibreGL and I inserted PMTiles in my code like this:
```
"tiles": ["pmtiles://sample.pmtiles/{z}/{x}/{y}"]
```

So I'm not sure what would be a URL in this case.

Thank you.

**Comment by bdon** [comment]
I have a little tile testing utility for siege at https://github.com/bdon/TileSiege , but it won't work this way with PMTiles; you would need to modify the `Range:` headers of the requests, and those request headers need to be based on the directory.

So you'll need a more advanced load testing library more likely, and it would simplify your tests to do random ~100KB requests instead of needing to base them off a directory.

**Comment by xinyuluo** [comment]
@bdon thanks. may I clarify what you mean by a random 100kb request test?

**Comment by bdon** [comment]
If you are load testing your server, there shouldn't be a meaningful difference between requesting random ranges like bytes 100000-200000, 300000-400000 and real tiles in the archive

**Comment by xinyuluo** [comment]
@bdon I see. Perhaps do you know of any more advanced load testing libraries that support tests on random ranges?
