### ISSUE TITLE
Display housenumbers

### ISSUE THREAD

**Issue by do-me** [protomaps/PMTiles#503]
I would like to include some custom labels, i.e. housenumbers in the basemap so that users might navigate more easily. If possible, I'd even like to include all address information so a user can get reverse geocoding right from the tiles, without external request to some API.

An example with housenumbers:
![image](https://github.com/user-attachments/assets/257b1642-990e-41cf-8887-cd0d9a05ba82)

This is the tooltip I'd like to display the address info in (screenshot from https://maps.protomaps.com/#map=18.69/48.1371319/11.5763067/-16.8/55&theme=light&lang=en&tiles=https://demo-bucket.protomaps.com/v4.pmtiles&npm_version=)
![image](https://github.com/user-attachments/assets/d223195e-1f23-4889-a14a-b1dd8b944291)

As far as I can tell, in the standard builds (https://maps.protomaps.com/builds/), this information is not included. Is there any documentation that would describe this process? Do you have a good recommendation where to start?

**Comment by do-me** [comment]
Thanks a lot for your super swift reply! 
I guess I should include all of these tags to nicely display housenumbers properly and without missing any https://taginfo.openstreetmap.org/keys/addr:housenumber#overview

![image](https://github.com/user-attachments/assets/9a861a4d-aef9-4d63-919f-19c2daccfe57)

I will give it a spin next week and see whether it works. Do you also have a pointer to a modified style json in case? 

> As a side remark the better repo to post this issue would be the basemap repo

You're right. Would it make sense to close this issue here and reopen it under basemaps or should I rather leave this one here open?

**Comment by wipfli** [comment]
I would close here and reopen in the basemap repo.

Before creating a style you can already check what is inside the tiles with
- pmtiles.io, or
- maputnik, or
- tileserver-gl

**Comment by bdon** [comment]
> I would like to include some custom labels, i.e. housenumbers in the basemap so that users might navigate more easily. If possible,

The general principle for including data in the protomaps basemap tileset is whether or not it appears in [tilezen](http://tilezen.readthedocs.io/en/latest/) visualized [here](http://tangrams.github.io/bubble-wrap/#20/37.78716/-122.39387) if you set labels to 11.

So we want to include housenumbers at the highest zoom. 

>  I'd even like to include all address information so a user can get reverse geocoding right from the tiles, without external request to some API.

This is not going to be in scope for the basemap, because many of the reverse geocoding information such as city, country it's in are not going to ever be included in the basemap because it would explode the tile size by a lot.

I would recommend using or reproducing the Overture Places PMTiles https://docs.overturemaps.org/examples/overture-tiles/ and adjusting to use OSM data and generate only a single zoom level such as 12, and include all places/division information specifically for reverse geocoding.

**Comment by do-me** [comment]
I think you're right, delivering the address details in the tiles for an on-click geocoder is not a good idea unless for very specific edge cases (working only on highest zoom levels where small tiles are delivered anyway).
Keeping it separate or as simple as possible with normal reverse geocoding requests on click make more sense.
